spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "2.0"

cards:
  message: "Welcome to Microservices World "
  contactDetails:
    name: "Pinki Kumari - Prod Lead"
    email: "pinki.kumari@outlook.com"
  onCallSupport:
    - (555) 555-1238
    - (555) 523-1349