spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to Microservices World "
  contactDetails:
    name: "Sony Behera - QA Lead"
    email: "sony.behera@outlook.com"
  onCallSupport:
    - (555) 555-1238
    - (555) 523-1349